version: '3'
    
services:

  rabbit:
    image: rabbitmq:alpine

  fib_generator:
    build: .
    restart: on-failure
    command: "fib_generator -c docker_config.yaml"
    depends_on:
      - database
      - rabbit
      - fib_consumer

  fib_consumer:
    build: .
    restart: on-failure
    command: "fib_consumer -c docker_config.yaml"
    depends_on:
      - database
      - rabbit

  fib_api:
      build: .
      restart: on-failure
      command: "fib_api -c docker_config.yaml"
      ports:
        - "8000:8000"
      depends_on:
        - fib_generator
        - fib_consumer
        - rabbit
        - database

  database:
    image: postgres:alpine
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres