# Path for debug.log, leave empty if no log is needed
debug_dirpath: ""

# Settings for API
api:
  host: "localhost"
  port: "80"

# Settings for Consumer
consumer:
  host: "localhost"
  routing_key: "fibonacci"

# Settings for generator
generator:
  host: "localhost"
  routing_key: "fibonacci"
  delay: 0.2

# Settings for database
database:
  provider: "postgresql"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: 1234
  db: "postgres"
