# Path for debug.log, leave empty if no log is needed
debug_dirpath: ""

# Settings for API
api:
  # Host that api will bind on
  host: "localhost"
  # Port that api will bind on
  port: "80"

# Settings for Consumer
consumer:
  # Host for rabbitmMQ
  host: "localhost"
  # Routing key for rabbitMQ
  routing_key: "fibonacci"

# Settings for generator
generator:
  # Host for rabbitMQ
  host: "localhost"
  # Routing key for rabbitMQ
  routing_key: "fibonacci"
  # Delay for generating numbers
  delay: 2

# Settings for database
database:
  provider: "postgresql"
  host: "localhost"
  db: "postgres"
  user: "postgres"
  port: 5432
  password: 1234
  
